import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  product: [

    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Nike Air Max 270',
      slug: 'nike-air-max-270',
      category: 'Shoes',
      image: '/images/shoe1.jpeg',
      price: 150,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 120,
      countInStock: 15,
      description: 'Stylish and comfortable running shoes',
    },
    {
      name: 'Adidas Ultraboost 22',
      slug: 'adidas-ultraboost-22',
      category: 'Shoes',
      image: '/images/shoe2.jpeg',
      price: 180,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 85,
      countInStock: 10,
      description: 'High-performance sneakers for athletes',
    },
    {
      name: 'Puma RS-X Sneakers',
      slug: 'puma-rs-x-sneakers',
      category: 'Shoes',
      image: '/images/shoe3.jpeg',
      price: 120,
      brand: 'Puma',
      rating: 4.6,
      numReviews: 60,
      countInStock: 25,
      description: 'Trendy and lightweight casual shoes',
    },
    {
      name: 'Reebok Classic Leather',
      slug: 'reebok-classic-leather',
      category: 'Shoes',
      image: '/images/shoe4.jpeg',
      price: 100,
      brand: 'Reebok',
      rating: 4.5,
      numReviews: 40,
      countInStock: 30,
      description: 'Timeless leather sneakers for everyday wear',
    },
    {
      name: 'The North Face Puffer Jacket',
      slug: 'north-face-puffer-jacket',
      category: 'Jackets',
      image: '/images/jacket1.jpeg',
      price: 200,
      brand: 'The North Face',
      rating: 4.8,
      numReviews: 95,
      countInStock: 12,
      description: 'Warm and insulated winter jacket',
    },
    {
      name: 'Columbia Waterproof Jacket',
      slug: 'columbia-waterproof-jacket',
      category: 'Jackets',
      image: '/images/jacket2.jpeg',
      price: 170,
      brand: 'Columbia',
      rating: 4.7,
      numReviews: 55,
      countInStock: 18,
      description: 'All-weather resistant outdoor jacket',
    },
    {
      name: 'Nike Sportswear Hoodie',
      slug: 'nike-sportswear-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie1.jpeg',
      price: 90,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 100,
      countInStock: 22,
      description: 'Soft fleece hoodie for casual wear',
    },
    {
      name: 'Adidas Essentials Hoodie',
      slug: 'adidas-essentials-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie2.jpeg',
      price: 85,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 80,
      countInStock: 15,
      description: 'Comfortable and stylish everyday hoodie',
    },
    {
      name: 'Under Armour Rival Hoodie',
      slug: 'under-armour-rival-hoodie',
      category: 'Hoodies',
      image: '/images/hoodie3.jpeg',
      price: 95,
      brand: 'Under Armour',
      rating: 4.7,
      numReviews: 60,
      countInStock: 18,
      description: 'Lightweight performance hoodie',
    },
    {
      name: 'Ugg Fluff Yeah Slippers',
      slug: 'ugg-fluff-yeah-slippers',
      category: 'Slippers',
      image: '/images/slipper1.jpeg',
      price: 110,
      brand: 'Ugg',
      rating: 4.8,
      numReviews: 45,
      countInStock: 12,
      description: 'Ultra-soft and cozy indoor slippers',
    },
    {
      name: 'Crocs Classic Clog',
      slug: 'crocs-classic-clog',
      category: 'Slippers',
      image: '/images/slipper2.jpeg',
      price: 60,
      brand: 'Crocs',
      rating: 4.6,
      numReviews: 85,
      countInStock: 20,
      description: 'Comfortable and breathable slippers',
    },
    {
      name: 'Rolex Submariner',
      slug: 'rolex-submariner',
      category: 'Watches',
      image: '/images/watch1.jpeg',
      price: 10000,
      brand: 'Rolex',
      rating: 5.0,
      numReviews: 20,
      countInStock: 5,
      description: 'Luxury stainless steel dive watch',
    },
    {
      name: 'Casio G-Shock GA2100',
      slug: 'casio-gshock-ga2100',
      category: 'Watches',
      image: '/images/watch2.jpeg',
      price: 120,
      brand: 'Casio',
      rating: 4.8,
      numReviews: 75,
      countInStock: 30,
      description: 'Durable and shock-resistant sports watch',
    },
  ],
}

export default data